name: Déploiement sur GitHub Pages

# Déclenche le workflow lors d'un push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Répertoire à publier